project:
  type: website
  output-dir: docs

website:
  title: "Analysis of U.S. Federal Holidays"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - icon: github
        href: https://github.com/xiaoranzhong0924

format:
  html:
    theme: cosmo
    css: styles.css





