project:
  type: website

website:
  title: "Analysis of U.S. Federal Holidays"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ETC5523-2024/assignment-3-v2-creating-a-blog-xiaoranzhong0924
format:
  html:
    theme: cosmo
    css: styles.css



